### ISSUE TITLE
no sound - pulseaudio

### ISSUE THREAD

**Issue by NoSequel** [gkisslinux/gcommunity#2]
I don't seem to have any incoming sound, `pamixer --list-sources` only seems to be outputting the dummy output;
`0 "auto_null.monitor" "Monitor of Dummy Output"`.

`alsactl init` seems to be outputting this:
`alsa-lib parser.c:2372:(load_toplevel_config) Unable to find the top-level configuration file '/usr/share/alsa/ucm2/ucm.conf'.
alsa-lib main.c:1405:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
Found hardware: "HDA-Intel" "Realtek ALCS1200A" "HDA:10ec0b00,18491204,00100001 HDA:8086280b,80860101,00100000" "0x1849" "0x1204"
Hardware is initialized using a generic method
alsa-lib parser.c:2372:(load_toplevel_config) Unable to find the top-level configuration file '/usr/share/alsa/ucm2/ucm.conf'.
alsa-lib main.c:1405:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -2
Found hardware: "HDA-Intel" "Nvidia GPU 71 HDMI/DP" "HDA:10de0071,19da2370,00100100" "0x19da" "0x2370"
Hardware is initialized using a generic method
`

I'm sorry if this is something stupid and easy to fix, but any help would be greatly appreciated!

**Comment by NoSequel** [comment]
oh and - updated kernel configuration (if it matters) can be found [here](https://termbin.com/3v51)

**Comment by NoSequel** [comment]
so far, still no luck in solving this issue. 

aplay -l: https://termbin.com/wm5g
lsmod: https://termbin.com/d0zp (recompiled kernel with snd_hd as a module instead of builtin, still not working though)

**Comment by git-bruh** [comment]
Sorry, haven't maintained this repository in a long while. You might have better luck with pipewire which can be found in my personal repo: 

https://github.com/git-bruh/kiss-repo/tree/master/repo/pipewire

Just install it and `ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/asound.conf` to make all alsa programs use pipewire (Remove any other .asoundrc or asound.conf). Just need to launch the daemon once by just running `pipewire`

**Comment by NoSequel** [comment]
> Sorry, haven't maintained this repository in a long while. You might have better luck with pipewire which can be found in my personal repo:
> 
> https://github.com/git-bruh/kiss-repo/tree/master/repo/pipewire
> 
> Just install it and `ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/asound.conf` to make all alsa programs use pipewire (Remove any other .asoundrc or asound.conf). Just need to launch the daemon once by just running `pipewire`

hey, I've just tried this, but with no luck whatsoever. Here is a related dicussion I've made on the official kiss linux repository with further details on my issue: https://github.com/kisslinux/repo/discussions/370
